@startuml App
'Location stores the coordinates'
class User {
    - firstName: string
    - lastName: string
    - email: string
    - password: string
    - points: int
    - range: int
    - picture: file
    - location: string
    + changeProfile(): void
    + changeLocation(): void
    + createNews(): void
}

class AreaOfInterest {
    - value: string
}

class Post {
    - title: string
    - content: string
    - likes: int
    - dateCreated: Date
    - dateEvent: Date
    - location: string
    + addSubscriber(user: User): void
    + removeSubscriber(user: User): void
}

class News {
    - title: string
    - link: string
}

class Notification {
    - content: string
    - user: User
}


User "*" -- "*" News
'A post can have more than one creator'
User "1" -- "*" Post: creates
User "*" -- "*" Post: liked
User "*" -- "*" Notification: receives
User "*" -- "1..4" AreaOfInterest
Post "*" -- "1..4" AreaOfInterest
User "*" -- "*" Post: subscribs
User "*" -- "*" Post: participated

@enduml
